import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { put } from '@vercel/blob'
import { getServerSession } from "next-auth/next"
import { authOptions } from "@/lib/auth"

export async function POST(request: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session || !session.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const formData = await request.formData();
    const file = formData.get('file') as File;
    const title = formData.get('title') as string;

    if (!file || !title) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    // Upload the file securely to Vercel Blob
    const blob = await put(file.name, file, {
      access: 'public',
      // Optionally restrict file types or size here if needed
    });

    // Give it a random height between 250px and 550px for the masonry layout
    const height = Math.floor(Math.random() * (550 - 250 + 1) + 250);

    // Save the metadata to our Postgres database using the Blob URL
    const artwork = await prisma.artwork.create({
      data: {
        title,
        height,
        userId: parseInt((session.user as any).id), // Use the securely authenticated user ID
        imageUrl: blob.url // URL generated by Vercel Blob
      }
    });

    return NextResponse.json({ success: true, artwork });
  } catch (error) {
    console.error('Upload Error:', error);
    return NextResponse.json({ error: 'Failed to upload artwork' }, { status: 500 });
  }
}
